### ISSUE TITLE
Problem running Karma tests after adding sidebar

### ISSUE THREAD

**Issue by perkka124** [arkon/ng2-sidebar#15]
This might be my fault when adding sidebar. But the sidebar shows up ok when running the website so it seems to work. The problem is that when running the karma tests I get the error pasted bellow. The problem seems to be that the array _closeDirectives.forEach is undefined for some reason when the test run. I'm new to javavscript and it seems to me like it could be the combination of tools that I use which triggers this issue. But I was thinking that it could be something to look at for stability reasons. I can send you the project that I have to trigger the issue if you are interested.

```
  Chrome 53.0.2785 (Mac OS X 10.11.6)
Error: Error in /Users/perka124/Documents/dev/Java/StoryTeller/ui/dist/dev/app/app.component.html:0:0 caused by: Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at Sidebar.ngOnDestroy (/Users/perka124/Documents/dev/Java/StoryTeller/ui/node_modules/ng2-sidebar/lib/sidebar.component.js:58:30)
    at DebugAppView._View_AppComponent0.destroyInternal (AppComponent.ngfactory.js:312:21)
    at DebugAppView.AppView.destroyLocal (/Users/perka124/Documents/dev/Java/StoryTeller/ui/node_modules/@angular/core/bundles/core.umd.js:9402:18)
    at DebugAppView.destroyLocal (/Users/perka124/Documents/dev/Java/StoryTeller/ui/node_modules/@angular/core/bundles/core.umd.js:9565:47)
    at DebugAppView.AppView._destroyRecurse (/Users/perka124/Documents/dev/Java/StoryTeller/ui/node_modules/@angular/core/bundles/core.umd.js:9390:18)
    at DebugAppView.AppView._destroyRecurse (/Users/perka124/Documents/dev/Java/StoryTeller/ui/node_modules/@angular/core/bundles/core.umd.js:9388:29)
    at DebugAppView.AppView._destroyRecurse (/Users/perka124/Documents/dev/Java/StoryTeller/ui/node_modules/@angular/core/bundles/core.umd.js:9388:29)
    at DebugAppView.AppView.destroy (/Users/perka124/Documents/dev/Java/StoryTeller/ui/node_modules/@angular/core/bundles/core.umd.js:9376:18)
    at ComponentRef_.destroy (/Users/perka124/Documents/dev/Java/StoryTeller/ui/node_modules/@angular/core/bundles/core.umd.js:5911:86)
    at ComponentFixture.destroy (/Users/perka124/Documents/dev/Java/StoryTeller/ui/node_modules/@angular/core/bundles/core-testing.umd.js:302:35)
    at eval (/Users/perka124/Documents/dev/Java/StoryTeller/ui/node_modules/@angular/core/bundles/core-testing.umd.js:760:78)
    at Array.forEach (native)
    at TestBed.resetTestingModule (/Users/perka124/Documents/dev/Java/StoryTeller/ui/node_modules/@angular/core/bundles/core-testing.umd.js:760:34)
    at Function.TestBed.resetTestingModule (/Users/perka124/Documents/dev/Java/StoryTeller/ui/node_modules/@angular/core/bundles/core-testing.umd.js:668:26)
    at Object.eval (/Users/perka124/Documents/dev/Java/StoryTeller/ui/node_modules/@angular/core/bundles/core-testing.umd.js:994:21)
    at ZoneDelegate.invoke (/Users/perka124/Documents/dev/Java/StoryTeller/ui/node_modules/zone.js/dist/zone.js:203:28)
    at ProxyZoneSpec.onInvoke (/Users/perka124/Documents/dev/Java/StoryTeller/ui/node_modules/zone.js/dist/proxy.js:72:39)
    at ZoneDelegate.invoke (/Users/perka124/Documents/dev/Java/StoryTeller/ui/node_modules/zone.js/dist/zone.js:202:34)
    at Zone.run (/Users/perka124/Documents/dev/Java/StoryTeller/ui/node_modules/zone.js/dist/zone.js:96:43)
    at Object.<anonymous> (/Users/perka124/Documents/dev/Java/StoryTeller/ui/node_modules/zone.js/dist/jasmine-patch.js:91:50)
    at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (/Users/perka124/Documents/dev/Java/StoryTeller/ui/node_modules/zone.js/dist/jasmine-patch.js:119:42)
    at ZoneDelegate.invokeTask (/Users/perka124/Documents/dev/Java/StoryTeller/ui/node_modules/zone.js/dist/zone.js:236:37)
    at Zone.runTask (/Users/perka124/Documents/dev/Java/StoryTeller/ui/node_modules/zone.js/dist/zone.js:136:47)
    at drainMicroTaskQueue (/Users/perka124/Documents/dev/Java/StoryTeller/ui/node_modules/zone.js/dist/zone.js:368:35)
    a
```

**Comment by arkon** [comment]
It might be potentially be [related to this](http://stackoverflow.com/questions/38479704/angular-2-unit-testing-component-mocking-contentchildren), but I'll keep looking into it.

**Comment by perkka124** [comment]
Yes, maybe. I'm just thinking that it is strange that the TypeScript array is compiled (or transpiled or what it's called) to a variable with undefined value even if the TypeScript array is empty. I did an ugly hack and added a nullcheck in the js file in my node_modules to be able to continue.

**Comment by arkon** [comment]
I published v1.6.1 with the null checks, but I'll keep this issue open so that I'll remember to investigate it more.

**Comment by perkka124** [comment]
Thanks! It works.

**Comment by arkon** [comment]
Thinking back on this, I think it's just because it's how Angular's ContentChildren/Query/QueryList stuff works.
